name: Node Setup
description: Node Setup

outputs:
  cache-hit:
    description: Informing if there has been cache hit on node_modules
    value: ${{ steps.node-modules.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'


    - name: Synchronize Node Modules cache
      id: node-modules
      uses: actions/cache@v3
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-


