name: 🧹 Purge jsDelivr Cache

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package name and version (e.g. cloudinary-video-player, cloudinary-video-player@1.0.0, or cloudinary-video-player@edge)'
        required: true
        default: 'cloudinary-video-player'
        type: string

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build distribution files
        run: npm run build-all

      - name: Purge jsDelivr Cache
        uses: ./.github/actions/purge-jsdelivr
        with:
          package: ${{ github.event.inputs.package }}

      - name: Summary
        run: |
          echo "### ✅ jsDelivr Cache Purge Complete" >> $GITHUB_STEP_SUMMARY
          echo "Package: \`${{ github.event.inputs.package }}\`" >> $GITHUB_STEP_SUMMARY
          echo "Files purged from jsDelivr CDN cache (excluding .map files)" >> $GITHUB_STEP_SUMMARY 
